# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.154.2+26.2

# Mod Properties
mod_version = 2.10.1
maven_group = com.tom5454.toms_storage
archives_base_name = toms_storage_fabric-26.2

cloth_config_version=26.2.155
rei_version=26.2.820
jei_version=30.7.0.41
